import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = {
  code: string;
  name: string;
  nativeName: string;
};

export const languages: Language[] = [
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "en", name: "English", nativeName: "English" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "en-ng", name: "Nigerian English", nativeName: "Nigerian English" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "fil", name: "Filipino", nativeName: "Filipino" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { code: "sr", name: "Serbian", nativeName: "Српски" },
];

type LanguageContextType = {
  currentLanguage: string;
  setLanguage: (code: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<string>(() => {
    return localStorage.getItem("language") || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", currentLanguage);
  }, [currentLanguage]);

  const setLanguage = (code: string) => {
    setCurrentLanguage(code);
  };

  const t = (key: string): string => {
    const translations = getTranslations(currentLanguage);
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

// Translation function
const getTranslations = (lang: string): Record<string, string> => {
  const translations: Record<string, Record<string, string>> = {
    sr: {
      // Header
      "choose_language": "Izaberi jezik",
      "profile": "Profil",
      "language": "Jezik",
      "privacy_policy": "Politika privatnosti",
      "terms_of_service": "Uslovi korišćenja",
      "my_account": "Moj nalog",
      
      // Sidebar
      "home": "Početna",
      "search": "Pretraži",
      "library": "Biblioteka",
      "create_playlist": "Napravi plejlistu",
      "favorites": "Omiljene pesme",
      "playlists": "Plejliste",
      
      // Footer
      "create": "Napravi",
      
      // Pi Authentication
      "welcome_user": "Dobrodošli, {username}! 👋",
      "premium_access_message": "Imate Premium pristup - uživajte u muzici bez ograničenja!",
      "logged_in_message": "Prijavljeni ste. Uživajte u muzici!",
      "sign_in_with_pi": "Prijavite se sa Pi",
      "sign_out": "Odjavi se",
      "go_premium": "Nabavi Premium",
      "premium_member": "Premium Član",
      "until": "Do",
      "processing_payment": "Obrađujem plaćanje...",
      "processing": "Obrađujem...",
      "activate": "Aktiviraj",
      "signing_in": "Prijavljujem se...",
      "please_sign_in": "Molimo prijavite se sa Pi...",
      "payment_processing": "🎉 Plaćanje se obrađuje... Proverite Pi novčanik!",
      "payment_failed": "⚠️ Plaćanje neuspešno:",
      "premium_version": "Premium Verzija",
      "premium_description": "Dobićete pristup ekskluzivnim funkcijama i pomoći ćete Purple Music!",
      "ad_free": "Slušajte bez reklama",
      "support_dev": "Podržite programera",
      "more_features": "Više funkcija uskoro",
      "weekly_plan": "Nedeljni plan",
      "monthly_plan": "Mesečni plan",
      "yearly_plan": "Godišnji plan",
      "days_access": "dana pristupa",
      "footer_note": "Vaš Pi novčanik će obraditi jednokratno plaćanje. Premium automatski ističe nakon izabranog perioda.",
      
      // Home page
      "welcome_back": "Dobrodošli nazad",
      "discover_music": "Otkrijte svoju omiljenu muziku",
      "search_placeholder": "Šta želite da slušate?",
      "featured_for_you": "Izdvojeno za vas",
      "recently_played": "Nedavno slušano",
      "popular_now": "Popularno sada",
      "by_mood": "Po raspoloženju",
      "by_genre": "Po žanru",
      
      // Library
      "your_library": "Vaša biblioteka",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "Moje Plejliste",
      "liked_playlists": "Omiljene Plejliste",
      "liked_songs": "Omiljene Pesme",
      "no_playlists_created": "Nemate kreiranih plejlista",
      "create_first_playlist": "Napravite svoju prvu plejlistu!",
      "no_liked_playlists": "Nemate omiljenih plejlista",
      "like_playlists_to_see_here": "Plejliste koje označite kao omiljene će se pojaviti ovde",
      "no_liked_songs": "Nemate omiljenih pesama",
      "like_songs_to_see_here": "Pesme koje označite kao omiljene će se pojaviti ovde",
      "loading": "Učitavanje",
      
      // Search
      "search_genre": "Pretražite po žanru",
      "popular": "Popularno",
      "popular_playlist": "Popularna plejlista",
      "most_popular_songs": "Najpopularnije pesme ovog žanra",
      
      // Favorites
      "playlist": "Plejlista",
      "favorite_songs": "Omiljene pesme",
      "your_collection": "Vaša kolekcija",
      "songs": "pesama",
      "title": "NASLOV",
      "album": "ALBUM",
      "date_added": "DATUM DODAVANJA",
      "no_favorites": "Nemate omiljenih pesama",
      "no_favorites_desc": "Pesme koje označite kao omiljene će se pojaviti ovde",
      "find_music": "Pronađi muziku",
      
      // Create Playlist
      "back": "Nazad",
      "create_new_playlist": "Napravi novu plejlistu",
      "add_image": "Dodaj sliku",
      "playlist_name": "Naziv plejliste",
      "my_playlist": "Moja Plejlista",
      "description_optional": "Opis (opciono)",
      "add_description": "Dodaj opis plejliste...",
      "create_playlist_btn": "Kreiraj plejlistu",
      "cancel": "Otkaži",
      "notes": "Napomene:",
      "note_1": "• Nakon kreiranja možete dodavati pesme u plejlistu",
      "note_2": "• Plejlista će biti privatna dok je ne podelite",
      "note_3": "• Možete je uvek urediti ili obrisati kasnije",
      "enter_playlist_name": "Unesite naziv plejliste",
      "playlist_created": "Plejlista kreirana!",
      
      // Playlist
      "user": "Korisnik",
    },
    en: {
      "choose_language": "Choose language",
      "profile": "Profile",
      "language": "Language",
      "privacy_policy": "Privacy Policy",
      "terms_of_service": "Terms of Service",
      "my_account": "My Account",
      "home": "Home",
      "search": "Search",
      "library": "Library",
      "create_playlist": "Create Playlist",
      "favorites": "Favorite Songs",
      "playlists": "Playlists",
      
      // Footer
      "create": "Create",
      
      // Pi Authentication
      "welcome_user": "Welcome, {username}! 👋",
      "premium_access_message": "You have Premium access - enjoy music without limits!",
      "logged_in_message": "You are signed in. Enjoy the music!",
      "sign_in_with_pi": "Sign in with Pi",
      "sign_out": "Sign out",
      "go_premium": "Go Premium",
      "premium_member": "Premium Member",
      "until": "Until",
      "processing_payment": "Processing payment...",
      "processing": "Processing...",
      "activate": "Activate",
      "signing_in": "Signing in...",
      "please_sign_in": "Please sign in with Pi first...",
      "payment_processing": "🎉 Payment processing... Please check your Pi wallet!",
      "payment_failed": "⚠️ Payment failed:",
      "premium_version": "Premium Version",
      "premium_description": "You'll get access to exclusive features and help improve Purple Music!",
      "ad_free": "Enjoy ad-free listening",
      "support_dev": "Support the developer",
      "more_features": "More features coming soon",
      "weekly_plan": "Weekly Plan",
      "monthly_plan": "Monthly Plan",
      "yearly_plan": "Yearly Plan",
      "days_access": "days access",
      "footer_note": "Your Pi wallet will process a one-time payment. Premium auto-expires after the selected period.",
      "welcome_back": "Welcome back",
      "discover_music": "Discover your favorite music",
      "search_placeholder": "What do you want to listen to?",
      "featured_for_you": "Featured for you",
      "recently_played": "Recently played",
      "popular_now": "Popular now",
      "by_mood": "By mood",
      "by_genre": "By genre",
      "your_library": "Your library",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
      "search_genre": "Browse by genre",
      "popular": "Popular",
      "popular_playlist": "Popular playlist",
      "most_popular_songs": "Most popular songs of this genre",
      "playlist": "Playlist",
      "favorite_songs": "Favorite Songs",
      "your_collection": "Your collection",
      "songs": "songs",
      "title": "TITLE",
      "album": "ALBUM",
      "date_added": "DATE ADDED",
      "no_favorites": "No favorite songs",
      "no_favorites_desc": "Songs you mark as favorites will appear here",
      "find_music": "Find music",
      "back": "Back",
      "create_new_playlist": "Create new playlist",
      "add_image": "Add image",
      "playlist_name": "Playlist name",
      "my_playlist": "My Playlist",
      "description_optional": "Description (optional)",
      "add_description": "Add playlist description...",
      "create_playlist_btn": "Create playlist",
      "cancel": "Cancel",
      "notes": "Notes:",
      "note_1": "• You can add songs to the playlist after creating it",
      "note_2": "• The playlist will be private until you share it",
      "note_3": "• You can always edit or delete it later",
      "enter_playlist_name": "Enter playlist name",
      "playlist_created": "Playlist created!",
      "user": "User",
    },
    es: {
      "choose_language": "Elegir idioma",
      "profile": "Perfil",
      "language": "Idioma",
      "privacy_policy": "Política de privacidad",
      "terms_of_service": "Términos de servicio",
      "my_account": "Mi cuenta",
      "home": "Inicio",
      "search": "Buscar",
      "library": "Biblioteca",
      "create_playlist": "Crear lista de reproducción",
      "favorites": "Canciones favoritas",
      "playlists": "Listas de reproducción",
      
      // Footer
      "create": "Crear",
      
      // Pi Authentication
      "welcome_user": "¡Bienvenido, {username}! 👋",
      "premium_access_message": "¡Tienes acceso Premium - disfruta de música sin límites!",
      "logged_in_message": "Has iniciado sesión. ¡Disfruta de la música!",
      "sign_in_with_pi": "Iniciar sesión con Pi",
      "sign_out": "Cerrar sesión",
      "go_premium": "Obtener Premium",
      "premium_member": "Miembro Premium",
      "until": "Hasta",
      "processing_payment": "Procesando pago...",
      "processing": "Procesando...",
      "activate": "Activar",
      "signing_in": "Iniciando sesión...",
      "please_sign_in": "Por favor, inicia sesión con Pi primero...",
      "payment_processing": "🎉 Procesando pago... ¡Por favor revisa tu billetera Pi!",
      "payment_failed": "⚠️ Pago fallido:",
      "premium_version": "Versión Premium",
      "premium_description": "¡Obtendrás acceso a funciones exclusivas y ayudarás a mejorar Purple Music!",
      "ad_free": "Disfruta sin anuncios",
      "support_dev": "Apoya al desarrollador",
      "more_features": "Más funciones próximamente",
      "weekly_plan": "Plan Semanal",
      "monthly_plan": "Plan Mensual",
      "yearly_plan": "Plan Anual",
      "days_access": "días de acceso",
      "footer_note": "Tu billetera Pi procesará un pago único. Premium expira automáticamente después del período seleccionado.",
      "welcome_back": "Bienvenido de nuevo",
      "discover_music": "Descubre tu música favorita",
      "search_placeholder": "¿Qué quieres escuchar?",
      "featured_for_you": "Destacado para ti",
      "recently_played": "Reproducido recientemente",
      "popular_now": "Popular ahora",
      "by_mood": "Por estado de ánimo",
      "by_genre": "Por género",
      "your_library": "Tu biblioteca",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
      "search_genre": "Navegar por género",
      "popular": "Popular",
      "popular_playlist": "Lista popular",
      "most_popular_songs": "Canciones más populares de este género",
      "playlist": "Lista",
      "favorite_songs": "Canciones favoritas",
      "your_collection": "Tu colección",
      "songs": "canciones",
      "title": "TÍTULO",
      "album": "ÁLBUM",
      "date_added": "FECHA AÑADIDA",
      "no_favorites": "No hay canciones favoritas",
      "no_favorites_desc": "Las canciones que marques como favoritas aparecerán aquí",
      "find_music": "Encontrar música",
      "back": "Volver",
      "create_new_playlist": "Crear nueva lista",
      "add_image": "Añadir imagen",
      "playlist_name": "Nombre de la lista",
      "my_playlist": "Mi Lista",
      "description_optional": "Descripción (opcional)",
      "add_description": "Añadir descripción de la lista...",
      "create_playlist_btn": "Crear lista",
      "cancel": "Cancelar",
      "notes": "Notas:",
      "note_1": "• Puedes añadir canciones a la lista después de crearla",
      "note_2": "• La lista será privada hasta que la compartas",
      "note_3": "• Siempre puedes editarla o eliminarla más tarde",
      "enter_playlist_name": "Ingresa el nombre de la lista",
      "playlist_created": "¡Lista creada!",
      "user": "Usuario",
    },
    fr: {
      "choose_language": "Choisir la langue",
      "profile": "Profil",
      "language": "Langue",
      "privacy_policy": "Politique de confidentialité",
      "terms_of_service": "Conditions d'utilisation",
      "my_account": "Mon compte",
      "home": "Accueil",
      "search": "Rechercher",
      "library": "Bibliothèque",
      "create_playlist": "Créer une playlist",
      "favorites": "Chansons favorites",
      "playlists": "Playlists",
      "create": "Créer",
      "welcome_user": "Bienvenue, {username}! 👋",
      "premium_access_message": "Vous avez un accès Premium - profitez de la musique sans limites!",
      "logged_in_message": "Vous êtes connecté. Profitez de la musique!",
      "sign_in_with_pi": "Se connecter avec Pi",
      "sign_out": "Se déconnecter",
      "go_premium": "Passer Premium",
      "premium_member": "Membre Premium",
      "until": "Jusqu'au",
      "processing_payment": "Traitement du paiement...",
      "processing": "Traitement...",
      "activate": "Activer",
      "signing_in": "Connexion en cours...",
      "please_sign_in": "Veuillez vous connecter avec Pi d'abord...",
      "payment_processing": "🎉 Paiement en cours... Veuillez vérifier votre portefeuille Pi!",
      "payment_failed": "⚠️ Paiement échoué:",
      "premium_version": "Version Premium",
      "premium_description": "Vous aurez accès à des fonctionnalités exclusives et aiderez à améliorer Purple Music!",
      "ad_free": "Écoute sans publicité",
      "support_dev": "Soutenir le développeur",
      "more_features": "Plus de fonctionnalités à venir",
      "weekly_plan": "Forfait Hebdomadaire",
      "monthly_plan": "Forfait Mensuel",
      "yearly_plan": "Forfait Annuel",
      "days_access": "jours d'accès",
      "footer_note": "Votre portefeuille Pi traitera un paiement unique. Premium expire automatiquement après la période sélectionnée.",
      "welcome_back": "Bienvenue",
      "discover_music": "Découvrez votre musique préférée",
      "search_placeholder": "Que voulez-vous écouter?",
      "featured_for_you": "Sélection pour vous",
      "recently_played": "Récemment joué",
      "popular_now": "Populaire maintenant",
      "by_mood": "Par humeur",
      "by_genre": "Par genre",
      "your_library": "Votre bibliothèque",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
      "search_genre": "Parcourir par genre",
      "popular": "Populaire",
      "popular_playlist": "Playlist populaire",
      "most_popular_songs": "Chansons les plus populaires de ce genre",
      "playlist": "Playlist",
      "favorite_songs": "Chansons favorites",
      "your_collection": "Votre collection",
      "songs": "chansons",
      "title": "TITRE",
      "album": "ALBUM",
      "date_added": "DATE AJOUTÉE",
      "no_favorites": "Aucune chanson favorite",
      "no_favorites_desc": "Les chansons que vous marquez comme favorites apparaîtront ici",
      "find_music": "Trouver de la musique",
      "back": "Retour",
      "create_new_playlist": "Créer une nouvelle playlist",
      "add_image": "Ajouter une image",
      "playlist_name": "Nom de la playlist",
      "my_playlist": "Ma Playlist",
      "description_optional": "Description (facultatif)",
      "add_description": "Ajouter une description de la playlist...",
      "create_playlist_btn": "Créer la playlist",
      "cancel": "Annuler",
      "notes": "Remarques:",
      "note_1": "• Vous pouvez ajouter des chansons à la playlist après sa création",
      "note_2": "• La playlist sera privée jusqu'à ce que vous la partagiez",
      "note_3": "• Vous pouvez toujours la modifier ou la supprimer plus tard",
      "enter_playlist_name": "Entrez le nom de la playlist",
      "playlist_created": "Playlist créée!",
      "user": "Utilisateur",
    },
    de: {
      "choose_language": "Sprache wählen",
      "profile": "Profil",
      "language": "Sprache",
      "privacy_policy": "Datenschutz",
      "terms_of_service": "Nutzungsbedingungen",
      "my_account": "Mein Konto",
      "home": "Startseite",
      "search": "Suchen",
      "library": "Bibliothek",
      "create_playlist": "Playlist erstellen",
      "favorites": "Lieblingssongs",
      "playlists": "Playlists",
      "create": "Erstellen",
      "welcome_user": "Willkommen, {username}! 👋",
      "premium_access_message": "Sie haben Premium-Zugang - genießen Sie Musik ohne Grenzen!",
      "logged_in_message": "Sie sind angemeldet. Genießen Sie die Musik!",
      "sign_in_with_pi": "Mit Pi anmelden",
      "sign_out": "Abmelden",
      "go_premium": "Premium werden",
      "premium_member": "Premium-Mitglied",
      "until": "Bis",
      "processing_payment": "Zahlung wird verarbeitet...",
      "processing": "Verarbeitung...",
      "activate": "Aktivieren",
      "signing_in": "Anmeldung läuft...",
      "please_sign_in": "Bitte melden Sie sich zuerst mit Pi an...",
      "payment_processing": "🎉 Zahlung wird verarbeitet... Bitte überprüfen Sie Ihre Pi-Wallet!",
      "payment_failed": "⚠️ Zahlung fehlgeschlagen:",
      "premium_version": "Premium-Version",
      "premium_description": "Sie erhalten Zugang zu exklusiven Funktionen und helfen Purple Music zu verbessern!",
      "ad_free": "Werbefreies Hören genießen",
      "support_dev": "Den Entwickler unterstützen",
      "more_features": "Weitere Funktionen folgen",
      "weekly_plan": "Wochenplan",
      "monthly_plan": "Monatsplan",
      "yearly_plan": "Jahresplan",
      "days_access": "Tage Zugang",
      "footer_note": "Ihre Pi-Wallet verarbeitet eine einmalige Zahlung. Premium läuft nach dem gewählten Zeitraum automatisch ab.",
      "welcome_back": "Willkommen zurück",
      "discover_music": "Entdecke deine Lieblingsmusik",
      "search_placeholder": "Was möchten Sie hören?",
      "featured_for_you": "Empfohlen für Sie",
      "recently_played": "Kürzlich gespielt",
      "popular_now": "Jetzt beliebt",
      "by_mood": "Nach Stimmung",
      "by_genre": "Nach Genre",
      "your_library": "Deine Bibliothek",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
      "search_genre": "Nach Genre durchsuchen",
      "popular": "Beliebt",
      "popular_playlist": "Beliebte Playlist",
      "most_popular_songs": "Beliebteste Songs dieses Genres",
      "playlist": "Playlist",
      "favorite_songs": "Lieblingssongs",
      "your_collection": "Deine Sammlung",
      "songs": "Songs",
      "title": "TITEL",
      "album": "ALBUM",
      "date_added": "HINZUGEFÜGT AM",
      "no_favorites": "Keine Lieblingssongs",
      "no_favorites_desc": "Songs, die du als Favoriten markierst, werden hier angezeigt",
      "find_music": "Musik finden",
      "back": "Zurück",
      "create_new_playlist": "Neue Playlist erstellen",
      "add_image": "Bild hinzufügen",
      "playlist_name": "Playlist-Name",
      "my_playlist": "Meine Playlist",
      "description_optional": "Beschreibung (optional)",
      "add_description": "Playlist-Beschreibung hinzufügen...",
      "create_playlist_btn": "Playlist erstellen",
      "cancel": "Abbrechen",
      "notes": "Hinweise:",
      "note_1": "• Du kannst nach dem Erstellen Songs zur Playlist hinzufügen",
      "note_2": "• Die Playlist bleibt privat, bis du sie teilst",
      "note_3": "• Du kannst sie jederzeit bearbeiten oder löschen",
      "enter_playlist_name": "Playlist-Namen eingeben",
      "playlist_created": "Playlist erstellt!",
      "user": "Benutzer",
    },
    it: {
      "choose_language": "Scegli lingua",
      "profile": "Profilo",
      "language": "Lingua",
      "privacy_policy": "Privacy",
      "terms_of_service": "Termini di servizio",
      "my_account": "Il mio account",
      "home": "Home",
      "search": "Cerca",
      "library": "Libreria",
      "create_playlist": "Crea playlist",
      "favorites": "Canzoni preferite",
      "playlists": "Playlist",
      "create": "Crea",
      "welcome_user": "Benvenuto, {username}! 👋",
      "premium_access_message": "Hai l'accesso Premium - goditi la musica senza limiti!",
      "logged_in_message": "Sei connesso. Goditi la musica!",
      "sign_in_with_pi": "Accedi con Pi",
      "sign_out": "Esci",
      "go_premium": "Passa a Premium",
      "premium_member": "Membro Premium",
      "until": "Fino al",
      "processing_payment": "Elaborazione pagamento...",
      "processing": "Elaborazione...",
      "activate": "Attiva",
      "signing_in": "Accesso in corso...",
      "please_sign_in": "Per favore accedi prima con Pi...",
      "payment_processing": "🎉 Pagamento in elaborazione... Controlla il tuo portafoglio Pi!",
      "payment_failed": "⚠️ Pagamento fallito:",
      "premium_version": "Versione Premium",
      "premium_description": "Avrai accesso a funzionalità esclusive e aiuterai a migliorare Purple Music!",
      "ad_free": "Ascolta senza pubblicità",
      "support_dev": "Sostieni lo sviluppatore",
      "more_features": "Altre funzionalità in arrivo",
      "weekly_plan": "Piano Settimanale",
      "monthly_plan": "Piano Mensile",
      "yearly_plan": "Piano Annuale",
      "days_access": "giorni di accesso",
      "footer_note": "Il tuo portafoglio Pi elaborerà un pagamento una tantum. Premium scade automaticamente dopo il periodo selezionato.",
      "welcome_back": "Bentornato",
      "discover_music": "Scopri la tua musica preferita",
      "search_placeholder": "Cosa vuoi ascoltare?",
      "featured_for_you": "In evidenza per te",
      "recently_played": "Riprodotti di recente",
      "popular_now": "Popolari ora",
      "by_mood": "Per umore",
      "by_genre": "Per genere",
      "your_library": "La tua libreria",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
      "search_genre": "Sfoglia per genere",
      "popular": "Popolare",
      "popular_playlist": "Playlist popolare",
      "most_popular_songs": "Canzoni più popolari di questo genere",
      "playlist": "Playlist",
      "favorite_songs": "Canzoni preferite",
      "your_collection": "La tua collezione",
      "songs": "canzoni",
      "title": "TITOLO",
      "album": "ALBUM",
      "date_added": "DATA AGGIUNTA",
      "no_favorites": "Nessuna canzone preferita",
      "no_favorites_desc": "Le canzoni che contrassegni come preferite appariranno qui",
      "find_music": "Trova musica",
      "back": "Indietro",
      "create_new_playlist": "Crea nuova playlist",
      "add_image": "Aggiungi immagine",
      "playlist_name": "Nome playlist",
      "my_playlist": "La mia Playlist",
      "description_optional": "Descrizione (facoltativo)",
      "add_description": "Aggiungi descrizione della playlist...",
      "create_playlist_btn": "Crea playlist",
      "cancel": "Annulla",
      "notes": "Note:",
      "note_1": "• Puoi aggiungere canzoni alla playlist dopo averla creata",
      "note_2": "• La playlist sarà privata finché non la condividi",
      "note_3": "• Puoi sempre modificarla o eliminarla in seguito",
      "enter_playlist_name": "Inserisci il nome della playlist",
      "playlist_created": "Playlist creata!",
      "user": "Utente",
    },
    pt: {
      "choose_language": "Escolher idioma",
      "profile": "Perfil",
      "language": "Idioma",
      "privacy_policy": "Política de privacidade",
      "terms_of_service": "Termos de serviço",
      "my_account": "Minha conta",
      "home": "Início",
      "search": "Pesquisar",
      "library": "Biblioteca",
      "create_playlist": "Criar playlist",
      "favorites": "Músicas favoritas",
      "playlists": "Playlists",
      "create": "Criar",
      "welcome_user": "Bem-vindo, {username}! 👋",
      "premium_access_message": "Você tem acesso Premium - aproveite música sem limites!",
      "logged_in_message": "Você está conectado. Aproveite a música!",
      "sign_in_with_pi": "Entrar com Pi",
      "sign_out": "Sair",
      "go_premium": "Obter Premium",
      "premium_member": "Membro Premium",
      "until": "Até",
      "processing_payment": "Processando pagamento...",
      "processing": "Processando...",
      "activate": "Ativar",
      "signing_in": "Entrando...",
      "please_sign_in": "Por favor, entre com Pi primeiro...",
      "payment_processing": "🎉 Pagamento processando... Por favor verifique sua carteira Pi!",
      "payment_failed": "⚠️ Pagamento falhou:",
      "premium_version": "Versão Premium",
      "premium_description": "Você terá acesso a recursos exclusivos e ajudará a melhorar o Purple Music!",
      "ad_free": "Aproveite sem anúncios",
      "support_dev": "Apoie o desenvolvedor",
      "more_features": "Mais recursos em breve",
      "weekly_plan": "Plano Semanal",
      "monthly_plan": "Plano Mensal",
      "yearly_plan": "Plano Anual",
      "days_access": "dias de acesso",
      "footer_note": "Sua carteira Pi processará um pagamento único. Premium expira automaticamente após o período selecionado.",
      "welcome_back": "Bem-vindo de volta",
      "discover_music": "Descubra sua música favorita",
      "search_placeholder": "O que você quer ouvir?",
      "featured_for_you": "Em destaque para você",
      "recently_played": "Tocado recentemente",
      "popular_now": "Popular agora",
      "by_mood": "Por humor",
      "by_genre": "Por gênero",
      "your_library": "Sua biblioteca",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
      "search_genre": "Navegar por gênero",
      "popular": "Popular",
      "popular_playlist": "Playlist popular",
      "most_popular_songs": "Músicas mais populares deste gênero",
      "playlist": "Playlist",
      "favorite_songs": "Músicas favoritas",
      "your_collection": "Sua coleção",
      "songs": "músicas",
      "title": "TÍTULO",
      "album": "ÁLBUM",
      "date_added": "DATA ADICIONADA",
      "no_favorites": "Nenhuma música favorita",
      "no_favorites_desc": "As músicas que você marcar como favoritas aparecerão aqui",
      "find_music": "Encontrar música",
      "back": "Voltar",
      "create_new_playlist": "Criar nova playlist",
      "add_image": "Adicionar imagem",
      "playlist_name": "Nome da playlist",
      "my_playlist": "Minha Playlist",
      "description_optional": "Descrição (opcional)",
      "add_description": "Adicionar descrição da playlist...",
      "create_playlist_btn": "Criar playlist",
      "cancel": "Cancelar",
      "notes": "Notas:",
      "note_1": "• Você pode adicionar músicas à playlist depois de criá-la",
      "note_2": "• A playlist será privada até você compartilhá-la",
      "note_3": "• Você sempre pode editá-la ou excluí-la depois",
      "enter_playlist_name": "Digite o nome da playlist",
      "playlist_created": "Playlist criada!",
      "user": "Usuário",
    },
    ru: {
      "choose_language": "Выбрать язык",
      "profile": "Профиль",
      "language": "Язык",
      "privacy_policy": "Политика конфиденциальности",
      "terms_of_service": "Условия использования",
      "my_account": "Мой аккаунт",
      "home": "Главная",
      "search": "Поиск",
      "library": "Библиотека",
      "create_playlist": "Создать плейлист",
      "favorites": "Избранные песни",
      "playlists": "Плейлисты",
      "create": "Создать",
      "welcome_user": "Добро пожаловать, {username}! 👋",
      "premium_access_message": "У вас есть Premium доступ - наслаждайтесь музыкой без ограничений!",
      "logged_in_message": "Вы вошли в систему. Наслаждайтесь музыкой!",
      "sign_in_with_pi": "Войти с Pi",
      "sign_out": "Выйти",
      "go_premium": "Получить Premium",
      "premium_member": "Premium Участник",
      "until": "До",
      "processing_payment": "Обработка платежа...",
      "processing": "Обработка...",
      "activate": "Активировать",
      "signing_in": "Вход...",
      "please_sign_in": "Пожалуйста, сначала войдите с Pi...",
      "payment_processing": "🎉 Платёж обрабатывается... Пожалуйста, проверьте ваш кошелёк Pi!",
      "payment_failed": "⚠️ Платёж не удался:",
      "premium_version": "Premium Версия",
      "premium_description": "Вы получите доступ к эксклюзивным функциям и поможете улучшить Purple Music!",
      "ad_free": "Слушайте без рекламы",
      "support_dev": "Поддержите разработчика",
      "more_features": "Больше функций скоро",
      "weekly_plan": "Недельный План",
      "monthly_plan": "Месячный План",
      "yearly_plan": "Годовой План",
      "days_access": "дней доступа",
      "footer_note": "Ваш кошелёк Pi обработает единовременный платёж. Premium автоматически истекает после выбранного периода.",
      "welcome_back": "С возвращением",
      "discover_music": "Откройте свою любимую музыку",
      "search_placeholder": "Что вы хотите послушать?",
      "featured_for_you": "Рекомендуем для вас",
      "recently_played": "Недавно прослушанное",
      "popular_now": "Популярное сейчас",
      "by_mood": "По настроению",
      "by_genre": "По жанру",
      "your_library": "Ваша библиотека",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
      "search_genre": "Обзор по жанрам",
      "popular": "Популярное",
      "popular_playlist": "Популярный плейлист",
      "most_popular_songs": "Самые популярные песни этого жанра",
      "playlist": "Плейлист",
      "favorite_songs": "Избранные песни",
      "your_collection": "Ваша коллекция",
      "songs": "песен",
      "title": "НАЗВАНИЕ",
      "album": "АЛЬБОМ",
      "date_added": "ДАТА ДОБАВЛЕНИЯ",
      "no_favorites": "Нет избранных песен",
      "no_favorites_desc": "Песни, которые вы отметите как избранные, появятся здесь",
      "find_music": "Найти музыку",
      "back": "Назад",
      "create_new_playlist": "Создать новый плейлист",
      "add_image": "Добавить изображение",
      "playlist_name": "Название плейлиста",
      "my_playlist": "Мой Плейлист",
      "description_optional": "Описание (необязательно)",
      "add_description": "Добавить описание плейлиста...",
      "create_playlist_btn": "Создать плейлист",
      "cancel": "Отмена",
      "notes": "Примечания:",
      "note_1": "• Вы можете добавить песни в плейлист после его создания",
      "note_2": "• Плейлист будет приватным, пока вы не поделитесь им",
      "note_3": "• Вы всегда можете отредактировать или удалить его позже",
      "enter_playlist_name": "Введите название плейлиста",
      "playlist_created": "Плейлист создан!",
      "user": "Пользователь",
    },
    tr: {
      "choose_language": "Dil seç",
      "profile": "Profil",
      "language": "Dil",
      "privacy_policy": "Gizlilik Politikası",
      "terms_of_service": "Hizmet Şartları",
      "home": "Ana Sayfa",
      "search": "Ara",
      "library": "Kütüphane",
      "create_playlist": "Çalma listesi oluştur",
      "favorites": "Favori şarkılar",
      "playlists": "Çalma listeleri",
      "create": "Oluştur",
      "welcome_user": "Hoş geldiniz, {username}! 👋",
      "premium_access_message": "Premium erişiminiz var - sınırsız müziğin tadını çıkarın!",
      "logged_in_message": "Giriş yaptınız. Müziğin tadını çıkarın!",
      "sign_in_with_pi": "Pi ile giriş yap",
      "sign_out": "Çıkış yap",
      "go_premium": "Premium'a Geç",
      "premium_member": "Premium Üye",
      "until": "Kadar",
      "processing_payment": "Ödeme işleniyor...",
      "processing": "İşleniyor...",
      "activate": "Etkinleştir",
      "signing_in": "Giriş yapılıyor...",
      "please_sign_in": "Lütfen önce Pi ile giriş yapın...",
      "payment_processing": "🎉 Ödeme işleniyor... Lütfen Pi cüzdanınızı kontrol edin!",
      "payment_failed": "⚠️ Ödeme başarısız:",
      "premium_version": "Premium Sürüm",
      "premium_description": "Özel özelliklere erişim kazanacak ve Purple Music'i geliştirmeye yardımcı olacaksınız!",
      "ad_free": "Reklamdan arınmış dinleme",
      "support_dev": "Geliştiriciye destek ol",
      "more_features": "Daha fazla özellik yakında",
      "weekly_plan": "Haftalık Plan",
      "monthly_plan": "Aylık Plan",
      "yearly_plan": "Yıllık Plan",
      "days_access": "gün erişim",
      "footer_note": "Pi cüzdanınız tek seferlik ödeme işleyecektir. Premium seçilen süre sonunda otomatik olarak sona erer.",
      "welcome_back": "Tekrar hoş geldiniz",
      "discover_music": "En sevdiğiniz müziği keşfedin",
      "search_placeholder": "Ne dinlemek istersiniz?",
      "featured_for_you": "Sizin için öne çıkanlar",
      "recently_played": "Son çalınanlar",
      "popular_now": "Şu an popüler",
      "by_mood": "Ruh haline göre",
      "by_genre": "Türe göre",
      "your_library": "Kütüphaneniz",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    hi: {
      "choose_language": "भाषा चुनें",
      "profile": "प्रोफ़ाइल",
      "language": "भाषा",
      "privacy_policy": "गोपनीयता नीति",
      "terms_of_service": "सेवा की शर्तें",
      "home": "होम",
      "search": "खोजें",
      "library": "लाइब्रेरी",
      "create_playlist": "प्लेलिस्ट बनाएं",
      "favorites": "पसंदीदा गाने",
      "playlists": "प्लेलिस्ट",
      "create": "बनाएं",
      "welcome_user": "स्वागत है, {username}! 👋",
      "premium_access_message": "आपके पास Premium एक्सेस है - बिना किसी सीमा के संगीत का आनंद लें!",
      "logged_in_message": "आप साइन इन हैं। संगीत का आनंद लें!",
      "sign_in_with_pi": "Pi के साथ साइन इन करें",
      "sign_out": "साइन आउट",
      "go_premium": "Premium प्राप्त करें",
      "premium_member": "Premium सदस्य",
      "until": "तक",
      "processing_payment": "भुगतान प्रसंस्करण...",
      "processing": "प्रसंस्करण...",
      "activate": "सक्रिय करें",
      "signing_in": "साइन इन...",
      "please_sign_in": "कृपया पहले Pi से साइन इन करें...",
      "payment_processing": "🎉 भुगतान प्रसंस्करण... कृपया अपने Pi वॉलेट की जांच करें!",
      "payment_failed": "⚠️ भुगतान विफल:",
      "premium_version": "Premium संस्करण",
      "premium_description": "आपको विशेष सुविधाओं तक पहुंच मिलेगी और Purple Music को बेहतर बनाने में मदद मिलेगी!",
      "ad_free": "विज्ञापन-मुक्त सुनने का आनंद लें",
      "support_dev": "डेवलपर का समर्थन करें",
      "more_features": "अधिक सुविधाएं जल्द आ रही हैं",
      "weekly_plan": "साप्ताहिक योजना",
      "monthly_plan": "मासिक योजना",
      "yearly_plan": "वार्षिक योजना",
      "days_access": "दिन की पहुंच",
      "footer_note": "आपका Pi वॉलेट एक बार का भुगतान संसाधित करेगा। Premium चयनित अवधि के बाद स्वचालित रूप से समाप्त हो जाता है।",
      "welcome_back": "वापसी पर स्वागत है",
      "discover_music": "अपना पसंदीदा संगीत खोजें",
      "search_placeholder": "आप क्या सुनना चाहते हैं?",
      "featured_for_you": "आपके लिए चुना गया",
      "recently_played": "हाल ही में चलाया गया",
      "popular_now": "अभी लोकप्रिय",
      "by_mood": "मूड के अनुसार",
      "by_genre": "शैली के अनुसार",
      "your_library": "आपकी लाइब्रेरी",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    ko: {
      "choose_language": "언어 선택",
      "profile": "프로필",
      "language": "언어",
      "privacy_policy": "개인정보 처리방침",
      "terms_of_service": "서비스 약관",
      "home": "홈",
      "search": "검색",
      "library": "라이브러리",
      "create_playlist": "재생목록 만들기",
      "favorites": "좋아하는 노래",
      "playlists": "재생목록",
      "create": "만들기",
      "welcome_user": "환영합니다, {username}! 👋",
      "premium_access_message": "Premium 액세스가 있습니다 - 제한 없이 음악을 즐기세요!",
      "logged_in_message": "로그인되었습니다. 음악을 즐기세요!",
      "sign_in_with_pi": "Pi로 로그인",
      "sign_out": "로그아웃",
      "go_premium": "Premium 받기",
      "premium_member": "Premium 회원",
      "until": "까지",
      "processing_payment": "결제 처리 중...",
      "processing": "처리 중...",
      "activate": "활성화",
      "signing_in": "로그인 중...",
      "please_sign_in": "먼저 Pi로 로그인해주세요...",
      "payment_processing": "🎉 결제 처리 중... Pi 지갑을 확인해주세요!",
      "payment_failed": "⚠️ 결제 실패:",
      "premium_version": "Premium 버전",
      "premium_description": "독점 기능에 액세스하고 Purple Music 개선에 도움을 주세요!",
      "ad_free": "광고 없이 즐기기",
      "support_dev": "개발자 지원하기",
      "more_features": "더 많은 기능 곧 출시",
      "weekly_plan": "주간 플랜",
      "monthly_plan": "월간 플랜",
      "yearly_plan": "연간 플랜",
      "days_access": "일 액세스",
      "footer_note": "Pi 지갑에서 일회성 결제를 처리합니다. Premium은 선택한 기간 후 자동으로 만료됩니다.",
      "welcome_back": "환영합니다",
      "discover_music": "좋아하는 음악을 발견하세요",
      "search_placeholder": "무엇을 듣고 싶으세요?",
      "featured_for_you": "추천 음악",
      "recently_played": "최근 재생한 음악",
      "popular_now": "지금 인기있는",
      "by_mood": "분위기별",
      "by_genre": "장르별",
      "your_library": "내 라이브러리",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    vi: {
      "choose_language": "Chọn ngôn ngữ",
      "profile": "Hồ sơ",
      "language": "Ngôn ngữ",
      "privacy_policy": "Chính sách bảo mật",
      "terms_of_service": "Điều khoản dịch vụ",
      "home": "Trang chủ",
      "search": "Tìm kiếm",
      "library": "Thư viện",
      "create_playlist": "Tạo danh sách phát",
      "favorites": "Bài hát yêu thích",
      "playlists": "Danh sách phát",
      "create": "Tạo",
      "welcome_user": "Chào mừng, {username}! 👋",
      "premium_access_message": "Bạn có quyền truy cập Premium - thưởng thức âm nhạc không giới hạn!",
      "logged_in_message": "Bạn đã đăng nhập. Thưởng thức âm nhạc!",
      "sign_in_with_pi": "Đăng nhập với Pi",
      "sign_out": "Đăng xuất",
      "go_premium": "Nhận Premium",
      "premium_member": "Thành viên Premium",
      "until": "Đến",
      "processing_payment": "Đang xử lý thanh toán...",
      "processing": "Đang xử lý...",
      "activate": "Kích hoạt",
      "signing_in": "Đang đăng nhập...",
      "please_sign_in": "Vui lòng đăng nhập với Pi trước...",
      "payment_processing": "🎉 Đang xử lý thanh toán... Vui lòng kiểm tra ví Pi của bạn!",
      "payment_failed": "⚠️ Thanh toán thất bại:",
      "premium_version": "Phiên bản Premium",
      "premium_description": "Bạn sẽ có quyền truy cập vào các tính năng độc quyền và giúp cải thiện Purple Music!",
      "ad_free": "Thưởng thức nghe nhạc không quảng cáo",
      "support_dev": "Hỗ trợ nhà phát triển",
      "more_features": "Nhiều tính năng hơn sắp ra mắt",
      "weekly_plan": "Gói Tuần",
      "monthly_plan": "Gói Tháng",
      "yearly_plan": "Gói Năm",
      "days_access": "ngày truy cập",
      "footer_note": "Ví Pi của bạn sẽ xử lý khoản thanh toán một lần. Premium tự động hết hạn sau thời gian đã chọn.",
      "welcome_back": "Chào mừng trở lại",
      "discover_music": "Khám phá nhạc yêu thích",
      "search_placeholder": "Bạn muốn nghe gì?",
      "featured_for_you": "Đề xuất cho bạn",
      "recently_played": "Phát gần đây",
      "popular_now": "Phổ biến hiện nay",
      "by_mood": "Theo tâm trạng",
      "by_genre": "Theo thể loại",
      "your_library": "Thư viện của bạn",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    th: {
      "choose_language": "เลือกภาษา",
      "profile": "โปรไฟล์",
      "language": "ภาษา",
      "privacy_policy": "นโยบายความเป็นส่วนตัว",
      "terms_of_service": "ข้อกำหนดการให้บริการ",
      "home": "หน้าแรก",
      "search": "ค้นหา",
      "library": "คลังเพลง",
      "create_playlist": "สร้างเพลย์ลิสต์",
      "favorites": "เพลงโปรด",
      "playlists": "เพลย์ลิสต์",
      "create": "สร้าง",
      "welcome_user": "ยินดีต้อนรับ, {username}! 👋",
      "premium_access_message": "คุณมีการเข้าถึง Premium - เพลิดเพลินกับเพลงไร้ขีดจำกัด!",
      "logged_in_message": "คุณเข้าสู่ระบบแล้ว เพลิดเพลินกับเพลง!",
      "sign_in_with_pi": "เข้าสู่ระบบด้วย Pi",
      "sign_out": "ออกจากระบบ",
      "go_premium": "รับ Premium",
      "premium_member": "สมาชิก Premium",
      "until": "จนถึง",
      "processing_payment": "กำลังดำเนินการชำระเงิน...",
      "processing": "กำลังดำเนินการ...",
      "activate": "เปิดใช้งาน",
      "signing_in": "กำลังเข้าสู่ระบบ...",
      "please_sign_in": "โปรดเข้าสู่ระบบด้วย Pi ก่อน...",
      "payment_processing": "🎉 กำลังดำเนินการชำระเงิน... โปรดตรวจสอบกระเป๋า Pi ของคุณ!",
      "payment_failed": "⚠️ การชำระเงินล้มเหลว:",
      "premium_version": "เวอร์ชัน Premium",
      "premium_description": "คุณจะได้รับฟีเจอร์พิเศษและช่วยปรับปรุง Purple Music!",
      "ad_free": "เพลิดเพลินกับการฟังแบบไม่มีโฆษณา",
      "support_dev": "สนับสนุนนักพัฒนา",
      "more_features": "ฟีเจอร์เพิ่มเติมเร็วๆ นี้",
      "weekly_plan": "แผนรายสัปดาห์",
      "monthly_plan": "แผนรายเดือน",
      "yearly_plan": "แผนรายปี",
      "days_access": "วันเข้าถึง",
      "footer_note": "กระเป๋า Pi ของคุณจะดำเนินการชำระเงินครั้งเดียว Premium จะหมดอายุโดยอัตโนมัติหลังจากช่วงเวลาที่เลือก",
      "welcome_back": "ยินดีต้อนรับกลับมา",
      "discover_music": "ค้นพบเพลงโปรดของคุณ",
      "search_placeholder": "คุณอยากฟังอะไร?",
      "featured_for_you": "แนะนำสำหรับคุณ",
      "recently_played": "เล่นล่าสุด",
      "popular_now": "ยอดนิยมตอนนี้",
      "by_mood": "ตามอารมณ์",
      "by_genre": "ตามประเภท",
      "your_library": "คลังของคุณ",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    id: {
      "choose_language": "Pilih bahasa",
      "profile": "Profil",
      "language": "Bahasa",
      "privacy_policy": "Kebijakan Privasi",
      "terms_of_service": "Syarat Layanan",
      "home": "Beranda",
      "search": "Cari",
      "library": "Pustaka",
      "create_playlist": "Buat daftar putar",
      "favorites": "Lagu favorit",
      "playlists": "Daftar putar",
      "create": "Buat",
      "welcome_user": "Selamat datang, {username}! 👋",
      "premium_access_message": "Anda memiliki akses Premium - nikmati musik tanpa batas!",
      "logged_in_message": "Anda sudah masuk. Nikmati musiknya!",
      "sign_in_with_pi": "Masuk dengan Pi",
      "sign_out": "Keluar",
      "go_premium": "Dapatkan Premium",
      "premium_member": "Anggota Premium",
      "until": "Sampai",
      "processing_payment": "Memproses pembayaran...",
      "processing": "Memproses...",
      "activate": "Aktifkan",
      "signing_in": "Masuk...",
      "please_sign_in": "Silakan masuk dengan Pi terlebih dahulu...",
      "payment_processing": "🎉 Pembayaran diproses... Silakan periksa dompet Pi Anda!",
      "payment_failed": "⚠️ Pembayaran gagal:",
      "premium_version": "Versi Premium",
      "premium_description": "Anda akan mendapatkan akses ke fitur eksklusif dan membantu meningkatkan Purple Music!",
      "ad_free": "Nikmati mendengarkan tanpa iklan",
      "support_dev": "Dukung pengembang",
      "more_features": "Fitur lebih banyak segera hadir",
      "weekly_plan": "Paket Mingguan",
      "monthly_plan": "Paket Bulanan",
      "yearly_plan": "Paket Tahunan",
      "days_access": "hari akses",
      "footer_note": "Dompet Pi Anda akan memproses pembayaran sekali. Premium akan kedaluwarsa otomatis setelah periode yang dipilih.",
      "welcome_back": "Selamat datang kembali",
      "discover_music": "Temukan musik favorit Anda",
      "search_placeholder": "Apa yang ingin Anda dengarkan?",
      "featured_for_you": "Unggulan untuk Anda",
      "recently_played": "Baru diputar",
      "popular_now": "Populer sekarang",
      "by_mood": "Berdasarkan suasana hati",
      "by_genre": "Berdasarkan genre",
      "your_library": "Pustaka Anda",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    bn: {
      "choose_language": "ভাষা নির্বাচন করুন",
      "profile": "প্রোফাইল",
      "language": "ভাষা",
      "privacy_policy": "গোপনীয়তা নীতি",
      "terms_of_service": "সেবার শর্তাবলী",
      "home": "হোম",
      "search": "অনুসন্ধান",
      "library": "লাইব্রেরি",
      "create_playlist": "প্লেলিস্ট তৈরি করুন",
      "favorites": "প্রিয় গান",
      "playlists": "প্লেলিস্ট",
      "create": "তৈরি করুন",
      "welcome_user": "স্বাগতম, {username}! 👋",
      "premium_access_message": "আপনার Premium অ্যাক্সেস আছে - সীমাহীন সঙ্গীত উপভোগ করুন!",
      "logged_in_message": "আপনি সাইন ইন করেছেন। সঙ্গীত উপভোগ করুন!",
      "sign_in_with_pi": "Pi দিয়ে সাইন ইন করুন",
      "sign_out": "সাইন আউট",
      "go_premium": "Premium পান",
      "premium_member": "Premium সদস্য",
      "until": "পর্যন্ত",
      "processing_payment": "পেমেন্ট প্রক্রিয়া করা হচ্ছে...",
      "processing": "প্রক্রিয়া করা হচ্ছে...",
      "activate": "সক্রিয় করুন",
      "signing_in": "সাইন ইন...",
      "please_sign_in": "অনুগ্রহ করে প্রথমে Pi দিয়ে সাইন ইন করুন...",
      "payment_processing": "🎉 পেমেন্ট প্রক্রিয়া করা হচ্ছে... আপনার Pi ওয়ালেট চেক করুন!",
      "payment_failed": "⚠️ পেমেন্ট ব্যর্থ:",
      "premium_version": "Premium সংস্করণ",
      "premium_description": "আপনি এক্সক্লুসিভ ফিচার অ্যাক্সেস পাবেন এবং Purple Music উন্নত করতে সাহায্য করবেন!",
      "ad_free": "বিজ্ঞাপন ছাড়া শুনুন",
      "support_dev": "ডেভেলপারকে সমর্থন করুন",
      "more_features": "আরো বৈশিষ্ট্য শীঘ্রই আসছে",
      "weekly_plan": "সাপ্তাহিক প্ল্যান",
      "monthly_plan": "মাসিক প্ল্যান",
      "yearly_plan": "বার্ষিক প্ল্যান",
      "days_access": "দিন অ্যাক্সেস",
      "footer_note": "আপনার Pi ওয়ালেট একবার পেমেন্ট প্রক্রিয়া করবে। নির্বাচিত সময়ের পর Premium স্বয়ংক্রিয়ভাবে মেয়াদ শেষ হবে।",
      "welcome_back": "ফিরে এসে স্বাগতম",
      "discover_music": "আপনার প্রিয় সঙ্গীত আবিষ্কার করুন",
      "search_placeholder": "আপনি কি শুনতে চান?",
      "featured_for_you": "আপনার জন্য বৈশিষ্ট্যযুক্ত",
      "recently_played": "সম্প্রতি বাজানো",
      "popular_now": "এখন জনপ্রিয়",
      "by_mood": "মেজাজ অনুযায়ী",
      "by_genre": "ধরন অনুযায়ী",
      "your_library": "আপনার লাইব্রেরি",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    pl: {
      "choose_language": "Wybierz język",
      "profile": "Profil",
      "language": "Język",
      "privacy_policy": "Polityka prywatności",
      "terms_of_service": "Warunki świadczenia usług",
      "home": "Strona główna",
      "search": "Szukaj",
      "library": "Biblioteka",
      "create_playlist": "Utwórz playlistę",
      "favorites": "Ulubione utwory",
      "playlists": "Playlisty",
      "create": "Utwórz",
      "welcome_back": "Witamy ponownie",
      "discover_music": "Odkryj swoją ulubioną muzykę",
      "search_placeholder": "Czego chcesz słuchać?",
      "featured_for_you": "Polecane dla Ciebie",
      "recently_played": "Ostatnio odtwarzane",
      "popular_now": "Popularne teraz",
      "by_mood": "Według nastroju",
      "by_genre": "Według gatunku",
      "your_library": "Twoja biblioteka",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    nl: {
      "choose_language": "Kies taal",
      "profile": "Profiel",
      "language": "Taal",
      "privacy_policy": "Privacybeleid",
      "terms_of_service": "Servicevoorwaarden",
      "home": "Home",
      "search": "Zoeken",
      "library": "Bibliotheek",
      "create_playlist": "Afspeellijst maken",
      "favorites": "Favoriete nummers",
      "playlists": "Afspeellijsten",
      "create": "Maken",
      "welcome_user": "Welkom, {username}! 👋",
      "premium_access_message": "Je hebt Premium toegang - geniet van muziek zonder grenzen!",
      "logged_in_message": "Je bent ingelogd. Geniet van de muziek!",
      "sign_in_with_pi": "Inloggen met Pi",
      "sign_out": "Uitloggen",
      "go_premium": "Premium worden",
      "premium_member": "Premium Lid",
      "until": "Tot",
      "processing_payment": "Betaling verwerken...",
      "processing": "Verwerken...",
      "activate": "Activeren",
      "signing_in": "Inloggen...",
      "please_sign_in": "Log eerst in met Pi...",
      "payment_processing": "🎉 Betaling wordt verwerkt... Controleer je Pi wallet!",
      "payment_failed": "⚠️ Betaling mislukt:",
      "premium_version": "Premium Versie",
      "premium_description": "Je krijgt toegang tot exclusieve functies en helpt Purple Music te verbeteren!",
      "ad_free": "Geniet van advertentievrij luisteren",
      "support_dev": "Ondersteun de ontwikkelaar",
      "more_features": "Meer functies binnenkort",
      "weekly_plan": "Weekplan",
      "monthly_plan": "Maandplan",
      "yearly_plan": "Jaarplan",
      "days_access": "dagen toegang",
      "footer_note": "Je Pi wallet verwerkt een eenmalige betaling. Premium verloopt automatisch na de geselecteerde periode.",
      "welcome_back": "Welkom terug",
      "discover_music": "Ontdek je favoriete muziek",
      "search_placeholder": "Wat wil je luisteren?",
      "featured_for_you": "Aanbevolen voor jou",
      "recently_played": "Recent afgespeeld",
      "popular_now": "Nu populair",
      "by_mood": "Op stemming",
      "by_genre": "Op genre",
      "your_library": "Jouw bibliotheek",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    cs: {
      "choose_language": "Vybrat jazyk",
      "profile": "Profil",
      "language": "Jazyk",
      "privacy_policy": "Zásady ochrany osobních údajů",
      "terms_of_service": "Podmínky služby",
      "home": "Domů",
      "search": "Hledat",
      "library": "Knihovna",
      "create_playlist": "Vytvořit playlist",
      "favorites": "Oblíbené písničky",
      "playlists": "Playlisty",
      "create": "Vytvořit",
      "welcome_user": "Vítejte, {username}! 👋",
      "premium_access_message": "Máte Premium přístup - užívejte si hudbu bez omezení!",
      "logged_in_message": "Jste přihlášeni. Užívejte si hudbu!",
      "sign_in_with_pi": "Přihlásit se s Pi",
      "sign_out": "Odhlásit se",
      "go_premium": "Získat Premium",
      "premium_member": "Premium Člen",
      "until": "Do",
      "processing_payment": "Zpracování platby...",
      "processing": "Zpracování...",
      "activate": "Aktivovat",
      "signing_in": "Přihlašování...",
      "please_sign_in": "Nejprve se přihlašte s Pi...",
      "payment_processing": "🎉 Platba se zpracovává... Zkontrolujte svou Pi peněženku!",
      "payment_failed": "⚠️ Platba selhala:",
      "premium_version": "Premium Verze",
      "premium_description": "Získáte přístup k exkluzivním funkcím a pomůžete zlepšit Purple Music!",
      "ad_free": "Užívejte si poslouch bez reklam",
      "support_dev": "Podpořte vývojáře",
      "more_features": "Další funkce brzy",
      "weekly_plan": "Týenní Plán",
      "monthly_plan": "Měsíční Plán",
      "yearly_plan": "Roční Plán",
      "days_access": "dní přístupu",
      "footer_note": "Vaše Pi peněženka zpracuje jednorázovou platbu. Premium automaticky vyprší po vybraném období.",
      "welcome_back": "Vítejte zpět",
      "discover_music": "Objevte svou oblíbenou hudbu",
      "search_placeholder": "Co chcete poslouchat?",
      "featured_for_you": "Doporučeno pro vás",
      "recently_played": "Nedávno přehrané",
      "popular_now": "Populární nyní",
      "by_mood": "Podle nálady",
      "by_genre": "Podle žánru",
      "your_library": "Vaše knihovna",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    hu: {
      "choose_language": "Nyelv kiválasztása",
      "profile": "Profil",
      "language": "Nyelv",
      "privacy_policy": "Adatvédelmi irányelvek",
      "terms_of_service": "Szolgáltatási feltételek",
      "home": "Kezdőlap",
      "search": "Keresés",
      "library": "Könyvtár",
      "create_playlist": "Lejátszási lista létrehozása",
      "favorites": "Kedvenc dalok",
      "playlists": "Lejátszási listák",
      "create": "Létrehozás",
      "welcome_back": "Üdvözöljük újra",
      "discover_music": "Fedezze fel kedvenc zenéjét",
      "search_placeholder": "Mit szeretne hallgatni?",
      "featured_for_you": "Ajánlott az Ön számára",
      "recently_played": "Nemrég játszott",
      "popular_now": "Most népszerű",
      "by_mood": "Hangulat szerint",
      "by_genre": "Műfaj szerint",
      "your_library": "Az Ön könyvtára",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    el: {
      "choose_language": "Επιλέξτε γλώσσα",
      "profile": "Προφίλ",
      "language": "Γλώσσα",
      "privacy_policy": "Πολιτική Απορρήτου",
      "terms_of_service": "Όροι Υπηρεσίας",
      "home": "Αρχική",
      "search": "Αναζήτηση",
      "library": "Βιβλιοθήκη",
      "create_playlist": "Δημιουργία λίστας",
      "favorites": "Αγαπημένα τραγούδια",
      "playlists": "Λίστες αναπαραγωγής",
      "create": "Δημιουργία",
      "welcome_back": "Καλώς ήρθατε πίσω",
      "discover_music": "Ανακαλύψτε την αγαπημένη σας μουσική",
      "search_placeholder": "Τι θέλετε να ακούσετε;",
      "featured_for_you": "Προτεινόμενα για εσάς",
      "recently_played": "Πρόσφατα παιγμένα",
      "popular_now": "Δημοφιλή τώρα",
      "by_mood": "Κατά διάθεση",
      "by_genre": "Κατά είδος",
      "your_library": "Η βιβλιοθήκη σας",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    ur: {
      "choose_language": "زبان منتخب کریں",
      "profile": "پروفائل",
      "language": "زبان",
      "privacy_policy": "رازداری کی پالیسی",
      "terms_of_service": "خدمات کی شرائط",
      "home": "ہوم",
      "search": "تلاش کریں",
      "library": "لائبریری",
      "create_playlist": "پلے لسٹ بنائیں",
      "favorites": "پسندیدہ گانے",
      "playlists": "پلے لسٹس",
      "create": "بنائیں",
      "welcome_user": "خوش آمدید, {username}! 👋",
      "premium_access_message": "آپ کے پاس Premium رسائی ہے - بغیر حد کے موسیقی سے لطف اندوز ہوں!",
      "logged_in_message": "آپ سائن ان ہیں۔ موسیقی سے لطف اندوز ہوں!",
      "sign_in_with_pi": "Pi کے ساتھ سائن ان کریں",
      "sign_out": "سائن آؤٹ",
      "go_premium": "Premium حاصل کریں",
      "premium_member": "Premium رکن",
      "until": "تک",
      "processing_payment": "ادائیگی کی کاروائی...",
      "processing": "کاروائی...",
      "activate": "فعال کریں",
      "signing_in": "سائن ان...",
      "please_sign_in": "براہ کرم پہلے Pi سے سائن ان کریں...",
      "payment_processing": "🎉 ادائیگی کی کاروائی... براہ کرم اپنے Pi بٹوئے کی جانچ کریں!",
      "payment_failed": "⚠️ ادائیگی ناکام:",
      "premium_version": "Premium ورژن",
      "premium_description": "آپ کو خصوصی خصوصیات تک رسائی ملے گی اور Purple Music کو بہتر بنانے میں مدد ملے گی!",
      "ad_free": "اشتہارات کے بغیر سنیں",
      "support_dev": "ڈیولپر کی حمایت کریں",
      "more_features": "مزید خصوصیات جلد آ رہی ہیں",
      "weekly_plan": "ہفتہ وار پلان",
      "monthly_plan": "ماہانہ پلان",
      "yearly_plan": "سالانہ پلان",
      "days_access": "دن کی رسائی",
      "footer_note": "آپ کا Pi بٹوا ایک بار کی ادائیگی کرے گا۔ منتخب مدت کے بعد Premium خودکار ختم ہو جاتا ہے۔",
      "welcome_back": "خوش آمدید",
      "discover_music": "اپنی پسندیدہ موسیقی دریافت کریں",
      "search_placeholder": "آپ کیا سننا چاہتے ہیں؟",
      "featured_for_you": "آپ کے لیے منتخب",
      "recently_played": "حال ہی میں چلایا گیا",
      "popular_now": "ابھی مقبول",
      "by_mood": "موڈ کے مطابق",
      "by_genre": "صنف کے مطابق",
      "your_library": "آپ کی لائبریری",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    ms: {
      "choose_language": "Pilih bahasa",
      "profile": "Profil",
      "language": "Bahasa",
      "privacy_policy": "Dasar Privasi",
      "terms_of_service": "Syarat Perkhidmatan",
      "home": "Laman Utama",
      "search": "Cari",
      "library": "Perpustakaan",
      "create_playlist": "Cipta senarai main",
      "favorites": "Lagu kegemaran",
      "playlists": "Senarai main",
      "create": "Cipta",
      "welcome_user": "Selamat datang, {username}! 👋",
      "premium_access_message": "Anda mempunyai akses Premium - nikmati muzik tanpa had!",
      "logged_in_message": "Anda telah log masuk. Nikmati muzik!",
      "sign_in_with_pi": "Log masuk dengan Pi",
      "sign_out": "Log keluar",
      "go_premium": "Dapatkan Premium",
      "premium_member": "Ahli Premium",
      "until": "Sehingga",
      "processing_payment": "Memproses bayaran...",
      "processing": "Memproses...",
      "activate": "Aktifkan",
      "signing_in": "Log masuk...",
      "please_sign_in": "Sila log masuk dengan Pi terlebih dahulu...",
      "payment_processing": "🎉 Bayaran sedang diproses... Sila semak dompet Pi anda!",
      "payment_failed": "⚠️ Bayaran gagal:",
      "premium_version": "Versi Premium",
      "premium_description": "Anda akan mendapat akses kepada ciri eksklusif dan membantu menambah baik Purple Music!",
      "ad_free": "Nikmati mendengar tanpa iklan",
      "support_dev": "Sokong pembangun",
      "more_features": "Lebih banyak ciri akan datang",
      "weekly_plan": "Pelan Mingguan",
      "monthly_plan": "Pelan Bulanan",
      "yearly_plan": "Pelan Tahunan",
      "days_access": "hari akses",
      "footer_note": "Dompet Pi anda akan memproses bayaran sekali. Premium akan tamat tempoh secara automatik selepas tempoh yang dipilih.",
      "welcome_back": "Selamat kembali",
      "discover_music": "Temui muzik kegemaran anda",
      "search_placeholder": "Apa yang anda ingin dengar?",
      "featured_for_you": "Dicadangkan untuk anda",
      "recently_played": "Dimainkan baru-baru ini",
      "popular_now": "Popular sekarang",
      "by_mood": "Mengikut mood",
      "by_genre": "Mengikut genre",
      "your_library": "Perpustakaan anda",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    fil: {
      "choose_language": "Pumili ng wika",
      "profile": "Profile",
      "language": "Wika",
      "privacy_policy": "Patakaran sa Privacy",
      "terms_of_service": "Mga Tuntunin ng Serbisyo",
      "home": "Home",
      "search": "Maghanap",
      "library": "Library",
      "create_playlist": "Gumawa ng playlist",
      "favorites": "Paboritong kanta",
      "playlists": "Mga playlist",
      "create": "Gumawa",
      "welcome_user": "Maligayang pagdating, {username}! 👋",
      "premium_access_message": "Mayroon kang Premium access - tamasahin ang musika nang walang hangganan!",
      "logged_in_message": "Naka-sign in ka na. Tamasahin ang musika!",
      "sign_in_with_pi": "Mag-sign in gamit ang Pi",
      "sign_out": "Mag-sign out",
      "go_premium": "Kumuha ng Premium",
      "premium_member": "Premium Member",
      "until": "Hanggang",
      "processing_payment": "Pinoproseso ang pagbabayad...",
      "processing": "Pinoproseso...",
      "activate": "I-activate",
      "signing_in": "Pumapasok...",
      "please_sign_in": "Mangyaring mag-sign in muna gamit ang Pi...",
      "payment_processing": "🎉 Pinoproseso ang pagbabayad... Pakisuri ang iyong Pi wallet!",
      "payment_failed": "⚠️ Nabigo ang pagbabayad:",
      "premium_version": "Premium na Bersyon",
      "premium_description": "Makakakuha ka ng access sa eksklusibong features at makakatulong sa pagpapabuti ng Purple Music!",
      "ad_free": "Tamasahin ang pakikinig nang walang ads",
      "support_dev": "Suportahan ang developer",
      "more_features": "Mas maraming features ay paparating",
      "weekly_plan": "Lingguhang Plano",
      "monthly_plan": "Buwanang Plano",
      "yearly_plan": "Taunang Plano",
      "days_access": "araw ng access",
      "footer_note": "Ang iyong Pi wallet ay magpoproseso ng isang beses na pagbabayad. Ang Premium ay awtomatikong mag-expire pagkatapos ng piniling panahon.",
      "welcome_back": "Maligayang pagbabalik",
      "discover_music": "Tuklasin ang iyong paboritong musika",
      "search_placeholder": "Ano ang gusto mong pakinggan?",
      "featured_for_you": "Inirekomenda para sa iyo",
      "recently_played": "Kamakailang pinatugtog",
      "popular_now": "Sikat ngayon",
      "by_mood": "Ayon sa mood",
      "by_genre": "Ayon sa genre",
      "your_library": "Ang iyong library",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    am: {
      "choose_language": "ቋንቋ ምረጥ",
      "profile": "መገለጫ",
      "language": "ቋንቋ",
      "privacy_policy": "የግላዊነት ፖሊሲ",
      "terms_of_service": "የአገልግሎት ውሎች",
      "home": "መነሻ",
      "search": "ፈልግ",
      "library": "ቤተ-መጽሐፍት",
      "create_playlist": "የአጫዋች ዝርዝር ፍጠር",
      "favorites": "የተወዳጁ ዘፈኖች",
      "playlists": "የአጫዋች ዝርዝሮች",
      "create": "ፍጠር",
      "welcome_user": "እንኳን ደህና መጣችሁ, {username}! 👋",
      "premium_access_message": "ልዩ ባህሪያት አግኝቶ ሙዚቃ ያለ ገደብ ይደሰቱ!",
      "logged_in_message": "ተገናኝተዋል። ሙዚቃውን ይደሰቱ!",
      "sign_in_with_pi": "በPi ይግቡ",
      "sign_out": "ይውጡ",
      "go_premium": "Premium ያግኙ",
      "premium_member": "Premium አባል",
      "until": "እስከ",
      "processing_payment": "ይግለጽውን ማስተናገድ...",
      "processing": "ማብራሪያ...",
      "activate": "አግልግል",
      "signing_in": "ይግባል...",
      "please_sign_in": "በመጀመሪያ በPi ይግቡ...",
      "payment_processing": "🎉 ይግለጽው ማስተናገድ... የPi አትሞችን ያረጋግጡ!",
      "payment_failed": "⚠️ ይግለጽው አልተሳካም:",
      "premium_version": "Premium ብርዝን",
      "premium_description": "ልዩ ባህሪያት አግኝቶ Purple Music መድበር ይዋጡሉ!",
      "ad_free": "ያልተአልን ማሰማሪያ",
      "support_dev": "አስተያይውን ይዋጡሉ",
      "more_features": "ተጨማሪ ባህሪያት ይመጣሉ",
      "weekly_plan": "ሳምንታዊ እቅድ",
      "monthly_plan": "ወራዊ እቅድ",
      "yearly_plan": "አመታዊ እቅድ",
      "days_access": "ቀናት አግልግሎት",
      "footer_note": "የPi አትሞች አንድ ጊዜ ይግለጽ ማብራሪያ። Premium ከተመረጠው ጊዜ በኋላ ራስሰር ይገባል።",
      "welcome_back": "እንኳን ደህና መጡ",
      "discover_music": "የእርስዎን ተወዳጅ ሙዚቃ ያግኙ",
      "search_placeholder": "ምን ማዳመጥ ይፈልጋሉ?",
      "featured_for_you": "ለእርስዎ የተመረጡ",
      "recently_played": "በቅርቡ የተጫወቱ",
      "popular_now": "አሁን ታዋቂ",
      "by_mood": "በስሜት",
      "by_genre": "በዘውግ",
      "your_library": "የእርስዎ ቤተ-መጽሐፍት",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
    "en-ng": {
      "choose_language": "Choose language",
      "profile": "Profile",
      "language": "Language",
      "privacy_policy": "Privacy Policy",
      "terms_of_service": "Terms of Service",
      "home": "Home",
      "search": "Search",
      "library": "Library",
      "create_playlist": "Create Playlist",
      "favorites": "Favourite Songs",
      "playlists": "Playlists",
      "create": "Create",
      "welcome_user": "Welcome, {username}! 👋",
      "premium_access_message": "You get Premium access - enjoy music without limits!",
      "logged_in_message": "You don sign in. Enjoy the music!",
      "sign_in_with_pi": "Sign in with Pi",
      "sign_out": "Sign out",
      "go_premium": "Get Premium",
      "premium_member": "Premium Member",
      "until": "Until",
      "processing_payment": "Processing payment...",
      "processing": "Processing...",
      "activate": "Activate",
      "signing_in": "Signing in...",
      "please_sign_in": "Please sign in with Pi first...",
      "payment_processing": "🎉 Payment dey process... Please check your Pi wallet!",
      "payment_failed": "⚠️ Payment fail:",
      "premium_version": "Premium Version",
      "premium_description": "You go get access to special features and help improve Purple Music!",
      "ad_free": "Enjoy ad-free listening",
      "support_dev": "Support the developer",
      "more_features": "More features dey come",
      "weekly_plan": "Weekly Plan",
      "monthly_plan": "Monthly Plan",
      "yearly_plan": "Yearly Plan",
      "days_access": "days access",
      "footer_note": "Your Pi wallet go process one-time payment. Premium go expire automatically after the selected period.",
      "welcome_back": "Welcome back",
      "discover_music": "Discover your favourite music",
      "search_placeholder": "Wetin you wan listen?",
      "featured_for_you": "Featured for you",
      "recently_played": "Recently played",
      "popular_now": "Popular now",
      "by_mood": "By mood",
      "by_genre": "By genre",
      "your_library": "Your library",
      "library_playlists": "My Playlists",
      "albums": "Liked Playlists",
      "artists": "Liked Songs",
      "my_playlists": "My Playlists",
      "liked_playlists": "Liked Playlists",
      "liked_songs": "Liked Songs",
      "no_playlists_created": "No playlists created",
      "create_first_playlist": "Create your first playlist!",
      "no_liked_playlists": "No liked playlists",
      "like_playlists_to_see_here": "Playlists you like will appear here",
      "no_liked_songs": "No liked songs",
      "like_songs_to_see_here": "Songs you like will appear here",
      "loading": "Loading",
    },
  };

  return translations[lang] || translations.en;
};
