import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = {
  code: string;
  name: string;
  nativeName: string;
};

export const languages: Language[] = [
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "en", name: "English", nativeName: "English" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "en-ng", name: "Nigerian English", nativeName: "Nigerian English" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "fil", name: "Filipino", nativeName: "Filipino" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { code: "sr", name: "Serbian", nativeName: "Српски" },
];

type LanguageContextType = {
  currentLanguage: string;
  setLanguage: (code: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<string>(() => {
    return localStorage.getItem("language") || "sr";
  });

  useEffect(() => {
    localStorage.setItem("language", currentLanguage);
  }, [currentLanguage]);

  const setLanguage = (code: string) => {
    setCurrentLanguage(code);
  };

  const t = (key: string): string => {
    const translations = getTranslations(currentLanguage);
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

// Translation function
const getTranslations = (lang: string): Record<string, string> => {
  const translations: Record<string, Record<string, string>> = {
    sr: {
      // Header
      "choose_language": "Izaberi jezik",
      "profile": "Profil",
      "language": "Jezik",
      "privacy_policy": "Politika privatnosti",
      "terms_of_service": "Uslovi korišćenja",
      
      // Sidebar
      "home": "Početna",
      "search": "Pretraži",
      "library": "Biblioteka",
      "create_playlist": "Napravi plejlistu",
      "favorites": "Omiljene pesme",
      "playlists": "Plejliste",
      
      // Footer
      "create": "Napravi",
      
      // Home page
      "welcome_back": "Dobrodošli nazad",
      "discover_music": "Otkrijte svoju omiljenu muziku",
      "search_placeholder": "Šta želite da slušate?",
      "featured_for_you": "Izdvojeno za vas",
      "recently_played": "Nedavno slušano",
      "popular_now": "Popularno sada",
      "by_mood": "Po raspoloženju",
      "by_genre": "Po žanru",
      
      // Library
      "your_library": "Vaša biblioteka",
      "albums": "Albumi",
      "artists": "Izvođači",
    },
    en: {
      "choose_language": "Choose language",
      "profile": "Profile",
      "language": "Language",
      "privacy_policy": "Privacy Policy",
      "terms_of_service": "Terms of Service",
      "home": "Home",
      "search": "Search",
      "library": "Library",
      "create_playlist": "Create Playlist",
      "favorites": "Favorite Songs",
      "playlists": "Playlists",
      "create": "Create",
      "welcome_back": "Welcome back",
      "discover_music": "Discover your favorite music",
      "search_placeholder": "What do you want to listen to?",
      "featured_for_you": "Featured for you",
      "recently_played": "Recently played",
      "popular_now": "Popular now",
      "by_mood": "By mood",
      "by_genre": "By genre",
      "your_library": "Your library",
      "albums": "Albums",
      "artists": "Artists",
    },
    es: {
      "choose_language": "Elegir idioma",
      "profile": "Perfil",
      "language": "Idioma",
      "privacy_policy": "Política de privacidad",
      "terms_of_service": "Términos de servicio",
      "home": "Inicio",
      "search": "Buscar",
      "library": "Biblioteca",
      "create_playlist": "Crear lista",
      "favorites": "Canciones favoritas",
      "playlists": "Listas",
      "create": "Crear",
      "welcome_back": "Bienvenido de nuevo",
      "discover_music": "Descubre tu música favorita",
      "search_placeholder": "¿Qué quieres escuchar?",
      "featured_for_you": "Destacado para ti",
      "recently_played": "Reproducido recientemente",
      "popular_now": "Popular ahora",
      "by_mood": "Por estado de ánimo",
      "by_genre": "Por género",
      "your_library": "Tu biblioteca",
      "albums": "Álbumes",
      "artists": "Artistas",
    },
    fr: {
      "choose_language": "Choisir la langue",
      "profile": "Profil",
      "language": "Langue",
      "privacy_policy": "Politique de confidentialité",
      "terms_of_service": "Conditions d'utilisation",
      "home": "Accueil",
      "search": "Rechercher",
      "library": "Bibliothèque",
      "create_playlist": "Créer une playlist",
      "favorites": "Chansons favorites",
      "playlists": "Playlists",
      "create": "Créer",
      "welcome_back": "Bienvenue",
      "discover_music": "Découvrez votre musique préférée",
      "search_placeholder": "Que voulez-vous écouter?",
      "featured_for_you": "Sélection pour vous",
      "recently_played": "Récemment joué",
      "popular_now": "Populaire maintenant",
      "by_mood": "Par humeur",
      "by_genre": "Par genre",
      "your_library": "Votre bibliothèque",
      "albums": "Albums",
      "artists": "Artistes",
    },
    de: {
      "choose_language": "Sprache wählen",
      "profile": "Profil",
      "language": "Sprache",
      "privacy_policy": "Datenschutz",
      "terms_of_service": "Nutzungsbedingungen",
      "home": "Startseite",
      "search": "Suchen",
      "library": "Bibliothek",
      "create_playlist": "Playlist erstellen",
      "favorites": "Lieblingssongs",
      "playlists": "Playlists",
      "create": "Erstellen",
      "welcome_back": "Willkommen zurück",
      "discover_music": "Entdecke deine Lieblingsmusik",
      "search_placeholder": "Was möchten Sie hören?",
      "featured_for_you": "Empfohlen für Sie",
      "recently_played": "Kürzlich gespielt",
      "popular_now": "Jetzt beliebt",
      "by_mood": "Nach Stimmung",
      "by_genre": "Nach Genre",
      "your_library": "Deine Bibliothek",
      "albums": "Alben",
      "artists": "Künstler",
    },
    it: {
      "choose_language": "Scegli lingua",
      "profile": "Profilo",
      "language": "Lingua",
      "privacy_policy": "Privacy",
      "terms_of_service": "Termini di servizio",
      "home": "Home",
      "search": "Cerca",
      "library": "Libreria",
      "create_playlist": "Crea playlist",
      "favorites": "Canzoni preferite",
      "playlists": "Playlist",
      "create": "Crea",
      "welcome_back": "Bentornato",
      "discover_music": "Scopri la tua musica preferita",
      "search_placeholder": "Cosa vuoi ascoltare?",
      "featured_for_you": "In evidenza per te",
      "recently_played": "Riprodotti di recente",
      "popular_now": "Popolari ora",
      "by_mood": "Per umore",
      "by_genre": "Per genere",
      "your_library": "La tua libreria",
      "albums": "Album",
      "artists": "Artisti",
    },
    pt: {
      "choose_language": "Escolher idioma",
      "profile": "Perfil",
      "language": "Idioma",
      "privacy_policy": "Política de privacidade",
      "terms_of_service": "Termos de serviço",
      "home": "Início",
      "search": "Pesquisar",
      "library": "Biblioteca",
      "create_playlist": "Criar playlist",
      "favorites": "Músicas favoritas",
      "playlists": "Playlists",
      "create": "Criar",
      "welcome_back": "Bem-vindo de volta",
      "discover_music": "Descubra sua música favorita",
      "search_placeholder": "O que você quer ouvir?",
      "featured_for_you": "Em destaque para você",
      "recently_played": "Tocado recentemente",
      "popular_now": "Popular agora",
      "by_mood": "Por humor",
      "by_genre": "Por gênero",
      "your_library": "Sua biblioteca",
      "albums": "Álbuns",
      "artists": "Artistas",
    },
    ru: {
      "choose_language": "Выбрать язык",
      "profile": "Профиль",
      "language": "Язык",
      "privacy_policy": "Политика конфиденциальности",
      "terms_of_service": "Условия использования",
      "home": "Главная",
      "search": "Поиск",
      "library": "Библиотека",
      "create_playlist": "Создать плейлист",
      "favorites": "Избранные песни",
      "playlists": "Плейлисты",
      "create": "Создать",
      "welcome_back": "С возвращением",
      "discover_music": "Откройте свою любимую музыку",
      "search_placeholder": "Что вы хотите послушать?",
      "featured_for_you": "Рекомендуем для вас",
      "recently_played": "Недавно прослушанное",
      "popular_now": "Популярное сейчас",
      "by_mood": "По настроению",
      "by_genre": "По жанру",
      "your_library": "Ваша библиотека",
      "albums": "Альбомы",
      "artists": "Исполнители",
    },
    tr: {
      "choose_language": "Dil seç",
      "profile": "Profil",
      "language": "Dil",
      "privacy_policy": "Gizlilik Politikası",
      "terms_of_service": "Hizmet Şartları",
      "home": "Ana Sayfa",
      "search": "Ara",
      "library": "Kütüphane",
      "create_playlist": "Çalma listesi oluştur",
      "favorites": "Favori şarkılar",
      "playlists": "Çalma listeleri",
      "create": "Oluştur",
      "welcome_back": "Tekrar hoş geldiniz",
      "discover_music": "En sevdiğiniz müziği keşfedin",
      "search_placeholder": "Ne dinlemek istersiniz?",
      "featured_for_you": "Sizin için öne çıkanlar",
      "recently_played": "Son çalınanlar",
      "popular_now": "Şu an popüler",
      "by_mood": "Ruh haline göre",
      "by_genre": "Türe göre",
      "your_library": "Kütüphaneniz",
      "albums": "Albümler",
      "artists": "Sanatçılar",
    },
    hi: {
      "choose_language": "भाषा चुनें",
      "profile": "प्रोफ़ाइल",
      "language": "भाषा",
      "privacy_policy": "गोपनीयता नीति",
      "terms_of_service": "सेवा की शर्तें",
      "home": "होम",
      "search": "खोजें",
      "library": "लाइब्रेरी",
      "create_playlist": "प्लेलिस्ट बनाएं",
      "favorites": "पसंदीदा गाने",
      "playlists": "प्लेलिस्ट",
      "create": "बनाएं",
      "welcome_back": "वापसी पर स्वागत है",
      "discover_music": "अपना पसंदीदा संगीत खोजें",
      "search_placeholder": "आप क्या सुनना चाहते हैं?",
      "featured_for_you": "आपके लिए चुना गया",
      "recently_played": "हाल ही में चलाया गया",
      "popular_now": "अभी लोकप्रिय",
      "by_mood": "मूड के अनुसार",
      "by_genre": "शैली के अनुसार",
      "your_library": "आपकी लाइब्रेरी",
      "albums": "एल्बम",
      "artists": "कलाकार",
    },
    ko: {
      "choose_language": "언어 선택",
      "profile": "프로필",
      "language": "언어",
      "privacy_policy": "개인정보 처리방침",
      "terms_of_service": "서비스 약관",
      "home": "홈",
      "search": "검색",
      "library": "라이브러리",
      "create_playlist": "재생목록 만들기",
      "favorites": "좋아하는 노래",
      "playlists": "재생목록",
      "create": "만들기",
      "welcome_back": "환영합니다",
      "discover_music": "좋아하는 음악을 발견하세요",
      "search_placeholder": "무엇을 듣고 싶으세요?",
      "featured_for_you": "추천 음악",
      "recently_played": "최근 재생한 음악",
      "popular_now": "지금 인기있는",
      "by_mood": "분위기별",
      "by_genre": "장르별",
      "your_library": "내 라이브러리",
      "albums": "앨범",
      "artists": "아티스트",
    },
    vi: {
      "choose_language": "Chọn ngôn ngữ",
      "profile": "Hồ sơ",
      "language": "Ngôn ngữ",
      "privacy_policy": "Chính sách bảo mật",
      "terms_of_service": "Điều khoản dịch vụ",
      "home": "Trang chủ",
      "search": "Tìm kiếm",
      "library": "Thư viện",
      "create_playlist": "Tạo danh sách phát",
      "favorites": "Bài hát yêu thích",
      "playlists": "Danh sách phát",
      "create": "Tạo",
      "welcome_back": "Chào mừng trở lại",
      "discover_music": "Khám phá nhạc yêu thích",
      "search_placeholder": "Bạn muốn nghe gì?",
      "featured_for_you": "Đề xuất cho bạn",
      "recently_played": "Phát gần đây",
      "popular_now": "Phổ biến hiện nay",
      "by_mood": "Theo tâm trạng",
      "by_genre": "Theo thể loại",
      "your_library": "Thư viện của bạn",
      "albums": "Album",
      "artists": "Nghệ sĩ",
    },
    th: {
      "choose_language": "เลือกภาษา",
      "profile": "โปรไฟล์",
      "language": "ภาษา",
      "privacy_policy": "นโยบายความเป็นส่วนตัว",
      "terms_of_service": "ข้อกำหนดการให้บริการ",
      "home": "หน้าแรก",
      "search": "ค้นหา",
      "library": "คลังเพลง",
      "create_playlist": "สร้างเพลย์ลิสต์",
      "favorites": "เพลงโปรด",
      "playlists": "เพลย์ลิสต์",
      "create": "สร้าง",
      "welcome_back": "ยินดีต้อนรับกลับมา",
      "discover_music": "ค้นพบเพลงโปรดของคุณ",
      "search_placeholder": "คุณอยากฟังอะไร?",
      "featured_for_you": "แนะนำสำหรับคุณ",
      "recently_played": "เล่นล่าสุด",
      "popular_now": "ยอดนิยมตอนนี้",
      "by_mood": "ตามอารมณ์",
      "by_genre": "ตามประเภท",
      "your_library": "คลังของคุณ",
      "albums": "อัลบั้ม",
      "artists": "ศิลปิน",
    },
    id: {
      "choose_language": "Pilih bahasa",
      "profile": "Profil",
      "language": "Bahasa",
      "privacy_policy": "Kebijakan Privasi",
      "terms_of_service": "Syarat Layanan",
      "home": "Beranda",
      "search": "Cari",
      "library": "Pustaka",
      "create_playlist": "Buat daftar putar",
      "favorites": "Lagu favorit",
      "playlists": "Daftar putar",
      "create": "Buat",
      "welcome_back": "Selamat datang kembali",
      "discover_music": "Temukan musik favorit Anda",
      "search_placeholder": "Apa yang ingin Anda dengarkan?",
      "featured_for_you": "Unggulan untuk Anda",
      "recently_played": "Baru diputar",
      "popular_now": "Populer sekarang",
      "by_mood": "Berdasarkan suasana hati",
      "by_genre": "Berdasarkan genre",
      "your_library": "Pustaka Anda",
      "albums": "Album",
      "artists": "Artis",
    },
    bn: {
      "choose_language": "ভাষা নির্বাচন করুন",
      "profile": "প্রোফাইল",
      "language": "ভাষা",
      "privacy_policy": "গোপনীয়তা নীতি",
      "terms_of_service": "সেবার শর্তাবলী",
      "home": "হোম",
      "search": "অনুসন্ধান",
      "library": "লাইব্রেরি",
      "create_playlist": "প্লেলিস্ট তৈরি করুন",
      "favorites": "প্রিয় গান",
      "playlists": "প্লেলিস্ট",
      "create": "তৈরি করুন",
      "welcome_back": "আবার স্বাগতম",
      "discover_music": "আপনার প্রিয় সঙ্গীত আবিষ্কার করুন",
      "search_placeholder": "আপনি কি শুনতে চান?",
      "featured_for_you": "আপনার জন্য বৈশিষ্ট্যযুক্ত",
      "recently_played": "সম্প্রতি বাজানো",
      "popular_now": "এখন জনপ্রিয়",
      "by_mood": "মেজাজ অনুযায়ী",
      "by_genre": "ধরন অনুযায়ী",
      "your_library": "আপনার লাইব্রেরি",
      "albums": "অ্যালবাম",
      "artists": "শিল্পী",
    },
    pl: {
      "choose_language": "Wybierz język",
      "profile": "Profil",
      "language": "Język",
      "privacy_policy": "Polityka prywatności",
      "terms_of_service": "Warunki świadczenia usług",
      "home": "Strona główna",
      "search": "Szukaj",
      "library": "Biblioteka",
      "create_playlist": "Utwórz playlistę",
      "favorites": "Ulubione utwory",
      "playlists": "Playlisty",
      "create": "Utwórz",
      "welcome_back": "Witamy ponownie",
      "discover_music": "Odkryj swoją ulubioną muzykę",
      "search_placeholder": "Czego chcesz słuchać?",
      "featured_for_you": "Polecane dla Ciebie",
      "recently_played": "Ostatnio odtwarzane",
      "popular_now": "Popularne teraz",
      "by_mood": "Według nastroju",
      "by_genre": "Według gatunku",
      "your_library": "Twoja biblioteka",
      "albums": "Albumy",
      "artists": "Artyści",
    },
    nl: {
      "choose_language": "Kies taal",
      "profile": "Profiel",
      "language": "Taal",
      "privacy_policy": "Privacybeleid",
      "terms_of_service": "Servicevoorwaarden",
      "home": "Home",
      "search": "Zoeken",
      "library": "Bibliotheek",
      "create_playlist": "Afspeellijst maken",
      "favorites": "Favoriete nummers",
      "playlists": "Afspeellijsten",
      "create": "Maken",
      "welcome_back": "Welkom terug",
      "discover_music": "Ontdek je favoriete muziek",
      "search_placeholder": "Wat wil je luisteren?",
      "featured_for_you": "Aanbevolen voor jou",
      "recently_played": "Recent afgespeeld",
      "popular_now": "Nu populair",
      "by_mood": "Op stemming",
      "by_genre": "Op genre",
      "your_library": "Jouw bibliotheek",
      "albums": "Albums",
      "artists": "Artiesten",
    },
    cs: {
      "choose_language": "Vybrat jazyk",
      "profile": "Profil",
      "language": "Jazyk",
      "privacy_policy": "Zásady ochrany osobních údajů",
      "terms_of_service": "Podmínky služby",
      "home": "Domů",
      "search": "Hledat",
      "library": "Knihovna",
      "create_playlist": "Vytvořit playlist",
      "favorites": "Oblíbené písničky",
      "playlists": "Playlisty",
      "create": "Vytvořit",
      "welcome_back": "Vítejte zpět",
      "discover_music": "Objevte svou oblíbenou hudbu",
      "search_placeholder": "Co chcete poslouchat?",
      "featured_for_you": "Doporučeno pro vás",
      "recently_played": "Nedávno přehrané",
      "popular_now": "Populární nyní",
      "by_mood": "Podle nálady",
      "by_genre": "Podle žánru",
      "your_library": "Vaše knihovna",
      "albums": "Alba",
      "artists": "Umělci",
    },
    hu: {
      "choose_language": "Nyelv kiválasztása",
      "profile": "Profil",
      "language": "Nyelv",
      "privacy_policy": "Adatvédelmi irányelvek",
      "terms_of_service": "Szolgáltatási feltételek",
      "home": "Kezdőlap",
      "search": "Keresés",
      "library": "Könyvtár",
      "create_playlist": "Lejátszási lista létrehozása",
      "favorites": "Kedvenc dalok",
      "playlists": "Lejátszási listák",
      "create": "Létrehozás",
      "welcome_back": "Üdvözöljük újra",
      "discover_music": "Fedezze fel kedvenc zenéjét",
      "search_placeholder": "Mit szeretne hallgatni?",
      "featured_for_you": "Ajánlott az Ön számára",
      "recently_played": "Nemrég játszott",
      "popular_now": "Most népszerű",
      "by_mood": "Hangulat szerint",
      "by_genre": "Műfaj szerint",
      "your_library": "Az Ön könyvtára",
      "albums": "Albumok",
      "artists": "Előadók",
    },
    el: {
      "choose_language": "Επιλέξτε γλώσσα",
      "profile": "Προφίλ",
      "language": "Γλώσσα",
      "privacy_policy": "Πολιτική Απορρήτου",
      "terms_of_service": "Όροι Υπηρεσίας",
      "home": "Αρχική",
      "search": "Αναζήτηση",
      "library": "Βιβλιοθήκη",
      "create_playlist": "Δημιουργία λίστας",
      "favorites": "Αγαπημένα τραγούδια",
      "playlists": "Λίστες αναπαραγωγής",
      "create": "Δημιουργία",
      "welcome_back": "Καλώς ήρθατε πίσω",
      "discover_music": "Ανακαλύψτε την αγαπημένη σας μουσική",
      "search_placeholder": "Τι θέλετε να ακούσετε;",
      "featured_for_you": "Προτεινόμενα για εσάς",
      "recently_played": "Πρόσφατα παιγμένα",
      "popular_now": "Δημοφιλή τώρα",
      "by_mood": "Κατά διάθεση",
      "by_genre": "Κατά είδος",
      "your_library": "Η βιβλιοθήκη σας",
      "albums": "Άλμπουμ",
      "artists": "Καλλιτέχνες",
    },
    ur: {
      "choose_language": "زبان منتخب کریں",
      "profile": "پروفائل",
      "language": "زبان",
      "privacy_policy": "رازداری کی پالیسی",
      "terms_of_service": "خدمات کی شرائط",
      "home": "ہوم",
      "search": "تلاش کریں",
      "library": "لائبریری",
      "create_playlist": "پلے لسٹ بنائیں",
      "favorites": "پسندیدہ گانے",
      "playlists": "پلے لسٹس",
      "create": "بنائیں",
      "welcome_back": "خوش آمدید",
      "discover_music": "اپنی پسندیدہ موسیقی دریافت کریں",
      "search_placeholder": "آپ کیا سننا چاہتے ہیں؟",
      "featured_for_you": "آپ کے لیے منتخب",
      "recently_played": "حال ہی میں چلایا گیا",
      "popular_now": "ابھی مقبول",
      "by_mood": "موڈ کے مطابق",
      "by_genre": "صنف کے مطابق",
      "your_library": "آپ کی لائبریری",
      "albums": "البمز",
      "artists": "فنکار",
    },
    ms: {
      "choose_language": "Pilih bahasa",
      "profile": "Profil",
      "language": "Bahasa",
      "privacy_policy": "Dasar Privasi",
      "terms_of_service": "Syarat Perkhidmatan",
      "home": "Laman Utama",
      "search": "Cari",
      "library": "Perpustakaan",
      "create_playlist": "Cipta senarai main",
      "favorites": "Lagu kegemaran",
      "playlists": "Senarai main",
      "create": "Cipta",
      "welcome_back": "Selamat kembali",
      "discover_music": "Temui muzik kegemaran anda",
      "search_placeholder": "Apa yang anda ingin dengar?",
      "featured_for_you": "Dicadangkan untuk anda",
      "recently_played": "Dimainkan baru-baru ini",
      "popular_now": "Popular sekarang",
      "by_mood": "Mengikut mood",
      "by_genre": "Mengikut genre",
      "your_library": "Perpustakaan anda",
      "albums": "Album",
      "artists": "Artis",
    },
    fil: {
      "choose_language": "Pumili ng wika",
      "profile": "Profile",
      "language": "Wika",
      "privacy_policy": "Patakaran sa Privacy",
      "terms_of_service": "Mga Tuntunin ng Serbisyo",
      "home": "Home",
      "search": "Maghanap",
      "library": "Library",
      "create_playlist": "Gumawa ng playlist",
      "favorites": "Paboritong kanta",
      "playlists": "Mga playlist",
      "create": "Gumawa",
      "welcome_back": "Maligayang pagbabalik",
      "discover_music": "Tuklasin ang iyong paboritong musika",
      "search_placeholder": "Ano ang gusto mong pakinggan?",
      "featured_for_you": "Inirekomenda para sa iyo",
      "recently_played": "Kamakailang pinatugtog",
      "popular_now": "Sikat ngayon",
      "by_mood": "Ayon sa mood",
      "by_genre": "Ayon sa genre",
      "your_library": "Ang iyong library",
      "albums": "Mga album",
      "artists": "Mga artista",
    },
    am: {
      "choose_language": "ቋንቋ ምረጥ",
      "profile": "መገለጫ",
      "language": "ቋንቋ",
      "privacy_policy": "የግላዊነት ፖሊሲ",
      "terms_of_service": "የአገልግሎት ውሎች",
      "home": "መነሻ",
      "search": "ፈልግ",
      "library": "ቤተ-መጽሐፍት",
      "create_playlist": "የአጫዋች ዝርዝር ፍጠር",
      "favorites": "ተወዳጅ ዘፈኖች",
      "playlists": "የአጫዋች ዝርዝሮች",
      "create": "ፍጠር",
      "welcome_back": "እንኳን ደህና መጡ",
      "discover_music": "የእርስዎን ተወዳጅ ሙዚቃ ያግኙ",
      "search_placeholder": "ምን ማዳመጥ ይፈልጋሉ?",
      "featured_for_you": "ለእርስዎ የተመረጡ",
      "recently_played": "በቅርቡ የተጫወቱ",
      "popular_now": "አሁን ታዋቂ",
      "by_mood": "በስሜት",
      "by_genre": "በዘውግ",
      "your_library": "የእርስዎ ቤተ-መጽሐፍት",
      "albums": "አልበሞች",
      "artists": "አርቲስቶች",
    },
    "en-ng": {
      "choose_language": "Choose language",
      "profile": "Profile",
      "language": "Language",
      "privacy_policy": "Privacy Policy",
      "terms_of_service": "Terms of Service",
      "home": "Home",
      "search": "Search",
      "library": "Library",
      "create_playlist": "Create Playlist",
      "favorites": "Favourite Songs",
      "playlists": "Playlists",
      "create": "Create",
      "welcome_back": "Welcome back",
      "discover_music": "Discover your favourite music",
      "search_placeholder": "Wetin you wan listen?",
      "featured_for_you": "Featured for you",
      "recently_played": "Recently played",
      "popular_now": "Popular now",
      "by_mood": "By mood",
      "by_genre": "By genre",
      "your_library": "Your library",
      "albums": "Albums",
      "artists": "Artists",
    },
  };

  return translations[lang] || translations.sr;
};
